= KMock
:link-base: https://github.com/bitPogo/
:link-repository: {link-base}kmock/
:project-version: 0.1.0
:doctype: article
:!showtitle:
:toc: macro
:toclevels: 2
:toc-title:
:icons: font
:imagesdir: assets/images
:lang: en
ifdef::env-github[]
:warning-caption: :warning:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
endif::[]

++++
<div align="center">
    <p><!-- PROJECT TITLE -->
        <h3>KMock</h3>
    </p>
    <p><!-- PROJECT DESCRIPTION -->
        A crossplatfrom mock framework for Kotlin (Multiplatform)
    </p>
    <p><!-- PROJECT DOCUMENTATION -->
        <a href="/docs/Index.adoc"><strong>Explore the docs »</strong></a>
    </p>
    <p><!-- PROJECT ISSUES/FEATURES -->
        <a href="https://github.com/bitPogo/kmock/issues">Report Bug</a>
        ·
        <a href="https://github.com/bitPogo/kmock/issues">Request Feature</a>
    </p>
    <p><!-- PROJECT BADGES see badges.adoc how to change them -->
        <!--<a href="https://github.com/bitPogo/kmock/releases">
            <img src="assets/images/badge-release-latest.svg" alt="Latest release"/>
        </a>//-->
        <a href="https://github.com/bitPogo/kmock/actions">
            <img src="https://github.com/bitPogo/kmock/actions/workflows/ci-latest-version.yml/badge.svg" alt="Latest Version"/>
        </a>
        <a>
            <img src="assets/images/badge-platform-support.svg" alt="Platform"/>
        </a>
        <a href="LICENSE">
            <img src="assets/images/badge-license.svg" alt="License"/>
        </a>
    </p>
</div>
++++

[discrete]
=== Table Of Contents

toc::[]

== About The Project

*Stop the war in Ukraine*

Mocking for tests should work without shenanigans or frills.
While link:https://mockk.io/[MockK] for example provides excellent support for Kotlin projects which operate on JVM, Multiplatform missing similar capabilities for quite some time.
KMock seeks to change that to a certain extend.
It supports for example arbitrary shared sources, spying and relaxing. +
If you want to learn about the usage and features please visit the link:{link-repository}/docs/chapters/QuickStarter.adoc[documentation] or
take a at the link:{link-base}kmock-playground[playground].

=== Dependencies

KMock has the following dependencies:

* link:https://developer.android.com/studio/releases/gradle-plugin[AndroidGradlePlugin (AGP) 7.1.2]
* link:https://kotlinlang.org/docs/releases.html[Kotlin 1.6.10]
* link:https://github.com/Kotlin/kotlinx.atomicfu[AtomicFu 0.17.1]
* link:https://github.com/touchlab/Stately[Touchlab's Stately 1.2.1]
* link:https://square.github.io/kotlinpoet/[Square KotlinPoet 1.10.2]
* link:https://github.com/google/ksp[Kotlin Symbol Processing (KSP) 1.6.10-1.0.4]
* link:https://gradle.org/[Gradle 7.2]

=== Additional Requirements

* Android 6.0 (API 23) to Android 12 (API 31)
* link:https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot[Java 11]

=== Built With

* link:https://kotlinlang.org/docs/reference/mpp-intro.html[Kotlin Multiplatform]

== Changelog

See link:CHANGELOG.adoc[changelog]

== Versioning

This project uses http://semver.org/[Semantic Versioning] as a guideline for our versioning.

Releases use this format: `{major}.{minor}.{patch}`

* Breaking changes bump `{major}` and reset `{minor}` & `{patch}`
* Backward compatible changes bump `{minor}` and reset `{patch}`
* Bug fixes bump `{patch}`

== Contributing

You want to help or share a proposal? You have a specific problem? Read the following:

* link:CODE-OF-CONDUCT.adoc[Code of conduct] for details on our code of conduct.
* link:CONTRIBUTING.adoc[Contributing] for details about how to report bugs and propose features.

== Copyright and License

Copyright (c) 2022 Matthias Geisler / All rights reserved.

Please refer to our link:LICENSE[License] for further details.
