= KMock
:link-base: https://github.com/bitPogo
:link-repository: {link-base}/kmock
:link-docs: {link-repository}/tree/main/docs
:project-version: 0.1.0
:doctype: article
:!showtitle:
:toc: macro
:toclevels: 2
:toc-title:
:icons: font
:imagesdir: assets/images
:lang: en
ifdef::env-github[]
:warning-caption: :warning:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
endif::[]

++++
<div align="center">
    <p><!-- PROJECT TITLE -->
        <h3>KMock</h3>
    </p>
    <p><!-- PROJECT DESCRIPTION -->
        A humble mocking library for Kotlin, KotlinJS and Kotlin Multiplatform using Kotlin Symbol Processing (KSP).
    </p>
    <p><!-- PROJECT DOCUMENTATION -->
        <a href="https://github.com/bitPogo/kmock/tree/main/docs"><strong>Explore the docs »</strong></a>
    </p>
    <p><!-- PROJECT ISSUES/FEATURES -->
        <a href="https://github.com/bitPogo/kmock/issues">Report Bug</a>
        ·
        <a href="https://github.com/bitPogo/kmock/issues">Request Feature</a>
    </p>
    <p><!-- PROJECT BADGES see badges.adoc how to change them -->
        <a href="https://github.com/bitPogo/kmock/releases">
            <img src="assets/images/badge-release-latest.svg" alt="Latest release"/>
        </a>
        <a href="https://github.com/bitPogo/kmock/actions">
            <img src="https://github.com/bitPogo/kmock/actions/workflows/ci-latest-version.yml/badge.svg" alt="Latest Version"/>
        </a>
        <a>
            <img src="assets/images/badge-platform-support.svg" alt="Platform"/>
        </a>
        <a href="LICENSE">
            <img src="assets/images/badge-license.svg" alt="License"/>
        </a>
    </p>
</div>
++++

[discrete]
== Table Of Contents

toc::[]

== About The Project
Writing mocks is certainly no witchcraft, but doing them by hand day for day can be dull.
More importantly it takes time which can be better invested directly into writing tests. +
However, while JVM projects get indeed supreme support by either link:https://mockk.io/[MockK] or link:https://github.com/mockito/mockito-kotlin[Mockito], KMP still has nothing comparable. +
KMock aims to at least automate the process of Mock generation and will hopefully advance from here.
Similar to other projects it uses link:https://github.com/google/ksp[KSP], but it is capable of associating generated Mocks correctly to their belonging shared source sets (like native, ios, etc) without additional setup and with minimal boilerplate done by consumers. +
KMock works currently *only* based on *interfaces*. It supports to some extent features like spying and relaxation of Mocks to make them non intrusive.
So if the project caught your eye check out the link:{link-base}/kmock-playground[Playground] or dive into the link:{link-docs}/StarterGuide.adoc[Starter Guide].

=== Dependencies

KMock has the following dependencies:

* link:https://developer.android.com/studio/releases/gradle-plugin[AndroidGradlePlugin (AGP) 7.1.2]
* link:https://kotlinlang.org/docs/releases.html[Kotlin 1.6.10]
* link:https://github.com/Kotlin/kotlinx.atomicfu[AtomicFu 0.17.1]
* link:https://github.com/touchlab/Stately[Touchlab's Stately 1.2.1]
* link:https://square.github.io/kotlinpoet/[Square KotlinPoet 1.10.2]
* link:https://github.com/google/ksp[Kotlin Symbol Processing (KSP) 1.6.10-1.0.4]
* link:https://gradle.org/[Gradle 7.2]

=== Additional Requirements

* Android 6.0 (API 23) to Android 12 (API 31)
* link:https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot[Java 11]

=== Built With

* link:https://kotlinlang.org/docs/reference/mpp-intro.html[Kotlin Multiplatform]

== Changelog

See link:CHANGELOG.adoc[changelog]

== Versioning

This project uses http://semver.org/[Semantic Versioning] as a guideline for our versioning.

Releases use this format: `{major}.{minor}.{patch}`

* Breaking changes bump `{major}` and reset `{minor}` & `{patch}`
* Backward compatible changes bump `{minor}` and reset `{patch}`
* Bug fixes bump `{patch}`

== Contributing

You want to help or share a proposal? You have a specific problem? Read the following:

* link:CODE-OF-CONDUCT.adoc[Code of conduct] for details on our code of conduct.
* link:CONTRIBUTING.adoc[Contributing] for details about how to report bugs and propose features.

== Copyright and License

Copyright (c) 2022 Matthias Geisler / All rights reserved.

Please refer to our link:LICENSE[License] for further details.
