= Banana-i18n-KMP
:link-repository: https://github.com/bitPogo/kmock
:project-version: 0.1.0
:doctype: article
:!showtitle:
:toc: macro
:toclevels: 2
:toc-title:
:icons: font
:imagesdir: assets/images
ifdef::env-github[]
:warning-caption: :warning:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
endif::[]

++++
<div align="center">
    <p><!-- PROJECT TITLE -->
        <h3>Antibytes  KMock library</h3>
    </p>
    <p><!-- PROJECT DESCRIPTION -->
        A crossplatfrom mock framework for Kotlin Multiplatform
    </p>
    <p><!-- PROJECT DOCUMENTATION -->
        <a href="README.adoc"><strong>Explore the docs »</strong></a>
    </p>
    <p><!-- PROJECT ISSUES/FEATURES -->
        <a href="https://github.com/bitPogo/kmock/issues">Report Bug</a>
        ·
        <a href="https://github.com/bitPogo/kmock/issues">Request Feature</a>
    </p>
    <p><!-- PROJECT BADGES see badges.adoc how to change them -->
        <a href="https://github.com/bitPogo/kmock/releases">
            <img src="assets/images/badge-release-latest.svg" alt="Latest release"/>
        </a>
        <a href="https://github.com/bitPogo/kmock/actions">
            <img src="https://github.com/bitPogo/kmock/actions/workflows/ci-latest-version.yml/badge.svg" alt="Latest Version"/>
        </a>
        <a>
            <img src="assets/images/badge-platform-support.svg" alt="Platform"/>
        </a>
        <a href="LICENSE">
            <img src="assets/images/badge-license.svg" alt="License"/>
        </a>
    </p>
</div>
++++

[discrete]
=== Table Of Contents

toc::[]

== About The Project

This project implements the message syntax for media wiki based on the original link:https://github.com/wikimedia/banana-i18n[Banana Project]

=== Dependencies

The SDK has the following dependencies:

== Installation

Coming soon.

=== Consume GitHub Packages

Coming soon.

==== Setup Maven Repository

Coming soon.

==== Common

Coming soon.

==== Android

Coming soon.

== Building and Working with the code base

There are several requirements for building the project.

=== Requirements

* Android 6.0 (API 23) to Android 11 (API 31)
* Kotlin 1.6.10
* Java 11 link:https://developer.android.com/studio/write/java11-support[Limitations] link:https://jakewharton.com/d8-library-desugaring/[Desugaring]
* Gradle 7.3.3
* link:https://developer.android.com/studio#downloads[Android Studio 7.1.0]
* Android Emulator 23 - 31

=== Built With

* link:https://kotlinlang.org/docs/reference/mpp-intro.html[Kotlin Multiplatform]

== Roadmap

Will be added soon.

== Changelog

See link:CHANGELOG.adoc[changelog]

== Versioning

We use http://semver.org/[Semantic Versioning] as a guideline for our versioning.

Releases use this format: `{major}.{minor}.{patch}`

* Breaking changes bump `{major}` and reset `{minor}` & `{patch}`
* Backward compatible changes bump `{minor}` and reset `{patch}`
* Bug fixes bump `{patch}`

== Contributing

You want to help or share a proposal? You have a specific problem? Read the following:

* link:CODE-OF-CONDUCT.adoc[Code of conduct] for details on our code of conduct.
* link:CONTRIBUTING.adoc[Contributing] for details about how to report bugs and propose features.
* link:DEVELOPING.adoc[Developing] for details about our development process and how to build and test the project.

== Copyright and License

Copyright (c) 2021 Matthias Geisler (bitPogo) / All rights reserved.

Please refer to our link:LICENSE[License] for further details.
