name: Antibytes CI - Latest Version

on:
  push:
    branches:
      - main
      - release/*

jobs:
  latest-version:

    runs-on: macos-latest

    env:
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_USERNAME }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_TOKEN }}

    steps:
      - name: Display runner context
        run: hostname -s
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
      - name: Cleanup
        run: ./gradlew clean
      - name: Build
        run: ./gradlew build
      - name: Publish to Snapshot Repository
        run: ./gradlew publishSnapshot --no-parallel
