name: Antibytes CI - Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-release:

    runs-on: macos-latest

    env:
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_USERNAME }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_TOKEN }}
      MAVEN_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASS }}
      MAVEN_KEY: ${{ secrets.MAVEN_GPG_KEY }}
      OSSR_USERNAME: ${{ secrets.OSSR_USERNAME }}
      OSSR_PASSWORD: ${{ secrets.OSSR_PASSWORD }}

    steps:
      - name: Display runner context
        run: hostname -s

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Cleanup
        run: ./gradlew clean

      - name: Build
        run: ./gradlew build

      - name: Prepare Python
        run: python3 -m pip install virtualenv --user

      - name: Publish documentation
        env:
          GRGIT_USER: ${{ github.actor }}
          GRGIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew --no-daemon --stacktrace mkdocsPublish -Prelease

      - name: Publish to Maven Central
        run: ./gradlew publishMavenCentral --stacktrace --no-parallel

      - name: Publish to Release Repository
        run: ./gradlew publishRelease --stacktrace --no-parallel
