name: Antibytes CI - Pull-Request Validation

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - main
      - release/*
      - core/*
      - plugin/*
      - bugfix/*
  workflow_dispatch:

jobs:
  pull-request-validation:

    runs-on: macos-latest

    concurrency:
      group: validation-${{ github.head_ref }}
      cancel-in-progress: true

    env:
      PACKAGE_REGISTRY_UPLOAD_USERNAME: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_USERNAME }}
      PACKAGE_REGISTRY_UPLOAD_TOKEN: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_TOKEN }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Cleanup
        run: ./gradlew clean

      - name: Lint
        run: ./gradlew spotlessCheck

      - name: Static Analysis
        run: ./gradlew detekt

      - name: Build
        run: ./gradlew build

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: failure()
        with:
          report_paths: '**/build/test-results/**/TEST-*.xml'

      - name: Quality Gate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew --no-daemon --stacktrace multiplatformCoverage sonarqube --info

      - name: Publish to Development Repository
        run: ./gradlew publishDevelopment --no-parallel

