name: Antibytes CI - Latest Version

on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    uses: bitpogo/workflows/.github/workflows/shared-build-macos.yml@main
    concurrency:
      group: build-linux-${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true

  coding-conventions:
    needs: build
    uses: bitpogo/workflows/.github/workflows/shared-coding-conventions-macos.yml@main
    with:
      cache-results: true
      detekt: true
      api-check: true
    concurrency:
      group: coding-conventions-${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true

  check-android:
    needs: build
    uses: bitpogo/workflows/.github/workflows/shared-test-android-macos.yml@main
    with:
      projects: "[':playground', ':integration-kmp', ':integration-android-application']"
      api-level: "['31']"
      arch: "['x86_64']"
      coverage: true
      cache-results: true
    concurrency:
      group: check-android-${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true

  coverage:
    needs: [ coding-conventions, check-android ]
    uses: bitpogo/workflows/.github/workflows/shared-coverage-macos.yml@main
    with:
      jvm: true
      verify-kmp: true
      cache-results: true
      use-sonar: true
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      sonar-token: ${{ secrets.SONAR_TOKEN }}
    concurrency:
      group: coverage
      cancel-in-progress: true

  check:
    needs: build
    uses: bitpogo/workflows/.github/workflows/shared-test-kmp.yml@main
    with:
      platforms: "['ios', 'linux-js']" #, 'mingw']"
    concurrency:
      group: check
      cancel-in-progress: true

  docs:
    needs: [ coverage, check ]
    uses: bitpogo/workflows/.github/workflows/shared-mkdocs-snapshot.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
    concurrency:
      group: docs
      cancel-in-progress: true

  publish:
    needs: [ coverage, check ]
    uses: bitpogo/workflows/.github/workflows/shared-publish-snapshot.yml@main
    secrets:
      upload-username: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_USERNAME }}
      upload-token: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_TOKEN }}
      maven-key: ${{ secrets.MAVEN_GPG_KEY }}
      maven-pass: ${{ secrets.MAVEN_GPG_PASS }}
    concurrency:
      group: publish
      cancel-in-progress: true
